ALTER TABLE "SiteConfig"
  ADD COLUMN IF NOT EXISTS "logoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "featuredClipsEyebrow" TEXT DEFAULT 'Clips destacados',
  ADD COLUMN IF NOT EXISTS "featuredClipsTitle" TEXT DEFAULT 'Shorts de los capitulos',
  ADD COLUMN IF NOT EXISTS "featuredClipsDescription" TEXT DEFAULT 'Fragmentos cortos para destacar ideas clave y llevar trafico al episodio completo.',
  ADD COLUMN IF NOT EXISTS "featuredClipsOrder" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "latestEpisodesEyebrow" TEXT DEFAULT 'Ultimos episodios',
  ADD COLUMN IF NOT EXISTS "latestEpisodesTitle" TEXT DEFAULT 'Conversaciones aplicadas a operaciones',
  ADD COLUMN IF NOT EXISTS "latestEpisodesDescription" TEXT DEFAULT 'Desde mejora continua hasta transformacion digital, con invitados del mundo industrial.',
  ADD COLUMN IF NOT EXISTS "latestEpisodesOrder" INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS "sponsorsSectionEyebrow" TEXT DEFAULT 'Sponsors',
  ADD COLUMN IF NOT EXISTS "sponsorsSectionTitle" TEXT DEFAULT 'Marcas alineadas con la industria',
  ADD COLUMN IF NOT EXISTS "sponsorsSectionDescription" TEXT DEFAULT 'Espacio para patrocinadores destacados y oportunidades de partnership por episodio.',
  ADD COLUMN IF NOT EXISTS "sponsorsSectionOrder" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS "recommendedSectionEyebrow" TEXT DEFAULT 'Recomendados',
  ADD COLUMN IF NOT EXISTS "recommendedSectionTitle" TEXT DEFAULT 'Episodios que merecen otra escucha',
  ADD COLUMN IF NOT EXISTS "recommendedSectionDescription" TEXT DEFAULT 'Selecciones editoriales para facilitar descubrimiento y aumentar tiempo de sesion.',
  ADD COLUMN IF NOT EXISTS "recommendedSectionOrder" INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS "guestsSectionEyebrow" TEXT DEFAULT 'Invitados',
  ADD COLUMN IF NOT EXISTS "guestsSectionTitle" TEXT DEFAULT 'Voces del ecosistema industrial',
  ADD COLUMN IF NOT EXISTS "guestsSectionDescription" TEXT DEFAULT 'Expertos, operadores y lideres que aterrizan teoria en ejecucion.',
  ADD COLUMN IF NOT EXISTS "guestsSectionOrder" INTEGER NOT NULL DEFAULT 5;
