ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityPageEyebrow" TEXT DEFAULT 'Comunidad';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityPageTitle" TEXT DEFAULT 'Encuestas, preguntas y contacto';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityPageDescription" TEXT DEFAULT 'Participa en preguntas generales o asociadas a capitulos especificos. Los comentarios quedan en la bandeja del administrador.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityEmptyTitle" TEXT DEFAULT 'No hay encuestas activas';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityEmptyDescription" TEXT DEFAULT 'Publica una encuesta desde el administrador para mostrarla aqui.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityContactTitle" TEXT DEFAULT 'Contactanos';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityContactDescription" TEXT DEFAULT 'Deja tu comentario e informacion de contacto para responderte despues.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "communityContactSubmitLabel" TEXT DEFAULT 'Enviar comentario';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "donationsContactTitle" TEXT DEFAULT 'Dejar datos para donar';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "donationsContactDescription" TEXT DEFAULT 'Completa el formulario y quedara en la bandeja del administrador para responderte.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "donationsContactSubmitLabel" TEXT DEFAULT 'Enviar datos';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "episodesPageEyebrow" TEXT DEFAULT 'Archivo';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "episodesPageTitle" TEXT DEFAULT 'Todos los episodios';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "episodesPageDescription" TEXT DEFAULT 'Explora el catalogo completo con lecturas limpias, links externos y relacion entre invitados, tags e industrias.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "guestsPageEyebrow" TEXT DEFAULT 'Invitados';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "guestsPageTitle" TEXT DEFAULT 'Personas que construyen industria';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "guestsPageDescription" TEXT DEFAULT 'Perfiles, empresas, enlaces sociales y episodios donde participan.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "sponsorsPageEyebrow" TEXT DEFAULT 'Sponsors';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "sponsorsPageTitle" TEXT DEFAULT 'Aliados comerciales del podcast';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "sponsorsPageDescription" TEXT DEFAULT 'Grid de logos, links de salida y sponsor destacado por episodio.';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "footerTitle" TEXT DEFAULT 'Industrial con J';
ALTER TABLE "SiteConfig" ADD COLUMN IF NOT EXISTS "footerDescription" TEXT DEFAULT 'Contenido para lideres de operaciones, ingenieria industrial y equipos que quieren escalar sistemas reales.';
